### ISSUE TITLE
Clicking a notification does not open the app/chat channel

### ISSUE THREAD

**Issue by JorenC** [zond/android-dipact#1]
When clicking a new message notification never opens the app/channel.

**Comment by zond** [comment]
This works for me, both in foreground, background, and when the app is off.

Could you give me more details?

**Comment by JorenC** [comment]
When I tap the notification it disappears, but I doesn't open the
application. Then I need to manually open the app and navigate to the chat
channel

**Comment by zond** [comment]
Are you sure you're using the latest version?

I just revamped the messaging system to make sure that turning notifications on and off again will actually refresh all settings correctly, so do that and then try again?

**Comment by JorenC** [comment]
Yes, I just checked. Latest version

**Comment by zond** [comment]
Did you try turning push messages off and on again?

**Comment by JorenC** [comment]
Yes, I turned them on and off in the app no difference. Let me clear cache
see if it still happens.

**Comment by zond** [comment]
I think this was fixed by cleaning up the FCM tokens. Use the "reset to default" in the settings menu for future reference.
